/***
 * common constant API Section for declaring urls
 ***/
export const API_URLS = {
  BASE_URL: "https://lmsapi.wjbeitler.com/api/",
  AZURE_FILE_UPLOAD_URL: "https://lmsafs.blob.core.windows.net/",
  FILE_END_POINT : 'https://lmsafs.file.core.windows.net/',
  TABLE_END_POINT : 'https://lmsafs.table.core.windows.net/',
  // SHARED_SIGNATURE:"SharedAccessSignature=sv=2020-08-04&ss=bfqt&srt=c&sp=rwdlacupitfx&se=2022-06-29T21:42:01Z&st=2021-12-17T13:42:01Z&spr=https&sig=DzFbVpBrEgGwU8NyanOTdkNBFPWX0alb6kxEq2GklBY%3D",
  SHARED_SIGNATURE:"SharedAccessSignature=sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2022-03-31T22:57:16Z&st=2022-01-03T14:57:16Z&spr=https&sig=Bvr9tf6JKekaMvPu4IGyeObgDXL%2FLqAorqRVr1jCZFc%3D",
  updateTableData: "api/update",
  login: "Auth/login",
  departments: "Shared/Departments",
  lookup: "Shared/lookup",
  notification_event: "notification/event",
  GET_NOTIFICATION_EVENT: "notification/event",
  notification_template: "notification/Template",
  notification_create: "notification/Queue/Create",
  validate_link: "validatelink",
  getPermissions: "Shared/Permissions",
  postPermissions: "Shared/Permission/create",
  putPermissions: "Shared/Permission/update",
  getEvents: "notification/event",
  postEvents: "notification/event/Create",
  putEvents: "notification/event/Update",
  getPermissionsGroup: "Shared/PermissionsGroup",
  postPermissionGroup: "Shared/PermissionGroup/create",
  putPermissionGroup: "Shared/PermissionGroup/update",
  validateUserName: "Auth/Validate/Username",
  updateUser: "Shared/User/update",
  REGISTER_USER: "User/register",
  contactType: "Shared/lookup?type=Contact_Type",
  getBrokers: "Shared/Broker",
  GET_CUSTOMER: "Shared/Customer",
  GET_CARRIER: "Shared/Carrier",
  GET_BROKER: "Shared/Broker",
  GET_CORPORATEBLS: "Shared/BLS",
  GET_POOLPROVIDER: "Shared/PoolProvider",
  GET_STORES: "Shared/Stores",
  CREATE_CUSTOMER: "Shared/Customer/Create",
  CREATE_CARRIER: "Shared/Carrier/Create",
  CREATE_BROKER: "Shared/Broker/Create",
  CREATE_POOL: "Shared/PoolProvider/Create",
  CREATE_STORE: "Shared/Store/Create",
  UPDATE_CUSTOMER: "Shared/Customer/Update",
  UPDATE_CARRIER: "Shared/Carrier/Update",
  UPDATE_BROKER: "Shared/Broker/Update",
  UPDATE_POOL: "Shared/PoolProvider/Update",
  UPDATE_STORE: "Shared/Store/Update",
  GET_NOTIFICATION_TEMPLATE: "notification/Template",
  CREATE_NOTIFICATION_TEMPLATE: "notification/Template/Create",
  UPDATE_NOTIFICATION_TEMPLATE: "notification/Template/Update",
  WEEK_MASTER: "Shared/WeekMaster",
  FUEL_SURCHARGE_UPLOAD: "Invoice/FuelSurcharge/upload",
  FUEL_SURCHARGE_LIST: "Invoice/FuelSurcharges",
  INTERLINE_UPLOAD: "Invoice/Interline/Upload",
  INTERLINE_LIST: "Invoice/Interline",
  ORDER_LIST: "Delivery/Order",
  DELIVERY_LIST: "Delivery/Delivery",
  DELIVERY_LIST_UPDATE: "v2/Delivery/Update",
  // DELIVERY_LIST_UPDATE: "Delivery/Delivery/Update",
  RATE_MASTER_UPLOAD: "Invoice/RatesMaster/Upload",
  GET_RATE_LIST: "Invoice/RatesMaster",
  CREATE_RATE: "Invoice/RatesMaster/Create",
  UPDATE_RATE: "Invoice/RatesMaster/Update",
  STORE_UPLOAD: "Shared/Store/Upload",
  GET_RATE_MASTER_BY_CUSTID: "Invoice/RatesMaster",
  GET_INVOICE_LIST: "Invoice/Invoice",
  CREATE_INVOICE: "Invoice/Invoice/Create",
  UPDATE_INVOICE: "Invoice/Invoice/Update",
  UPDATE_LAST_INVOICE_NUMBER: "Invoice/Invoice/UpdateLookUpByType",
  CREATE_PURCHASE_JOURNAL_INVOICE: "Invoice/PurchaseJournal/Create",
  UPDATE_PURCHASE_JOURNAL_INVOICE: "Invoice/PurchaseJournal/Update",
  GET_FUELPRICE_HISTORY_LIST: "Invoice/FuelPriceHistory",
  GET_PURCHASE_JOURNAL_LIST: "Invoice/PurchaseJournal",
  ADD_EDI:'EDI/Queue/Create',
  GET_EDI_QUEUE_LIST: "EDI/Queue",
  GET_VENDOR:'Shared/Vendor',
  UPDATE_VENDOR: "Shared/Vendor/Update",
  CREATE_VENDOR: "Shared/Vendor/Create",
  GET_RULES: "notification/Rules",
  POST_RULES: "notification/Rules/Create",
  UPDATE_RULES: "notification/Rules/Update",
};
